name: Deploy Angular Application

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
           set -exu
           cd /root/angular/angularapp/
           git pull
           npm ci
           npm run build
           set -exu
           rm -rf /var/www/dist
           mv /root/angular/angularapp/dist /var/www/
           systemctl reload nginx.service

