name: Deploy Angular Application

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.0.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
           rm -rf /var/www/dist
           cd angular/
           git pull
           npm run build
           set -exu
           mv /home/root/angular/dist /var/www/
           systemctl reload nginx.service

